<div class="clear"></div>
<hr>

<h1>
    <strong><?php echo ComentarismoWP::$plugin_name; ?> Pro Version</strong>
</h1>

<p>
    If you like the <?php echo ComentarismoWP::$plugin_name; ?> but you're missing some features, probably you can find it in the Premium version.
    <br/>
    We have prepared lists of features which you can find in one of the Premium version of <a title="<?php echo ComentarismoWP::$plugin_name; ?>" href="<?php echo ComentarismoWP::$plugin_user_guide; ?>"><?php echo ComentarismoWP::$plugin_name; ?></a>.
</p>

<div class="clear"></div>

<br/><br/>

<h2>Features (Pro Version Only)</h2>

<ul>
    <li><strong>Support custom post types</strong> - free version works only for posts and pages</li>
    <li><strong>Add Script Title</strong> - to name or describe each script</li>
    <li><strong>Add Script Settings metabox to post edit screen</strong> - which allows to to disable/enable scripts for single post/page</li>
</ul>

<h1><strong>Purchase </strong></h1>
<p>You can purchase the Pro version <a class="button button-primary" href="<?php echo ComentarismoWP::$plugin_user_guide; ?>">Here</a></p>